#!/bin/bash
# script for configuring and bmaking sys kernel
# takes assignment number as user input
# remember to call with . (ex: . build_ASST 1)
cd ~/cs350-os161/os161-1.99/kern/conf
assign="ASST"
assign="$assign${1}"
./config $assign
cd ../compile/$assign
bmake depend
bmake
bmake install
cd ~/cs350-os161/root
